services:
  - type: web
    name: telegram-spam-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
